/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import cashier.*;
import Login.LoginForm;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AMIFAH
 */
public class ManagerReportForm extends javax.swing.JFrame {

    /**
     * Creates new form ReportForm
     */
    public ManagerReportForm() {
        initComponents();
    
       Amount.setText(Double.toString( getSum()));
        
    }
    
    public double getSum(){
        
        double sum=ReportTable.getRowCount();
        double total=0;
        for (double i=0; i<sum;i++){
            total = total + Double.parseDouble(ReportTable.getValueAt((int) i, 7).toString());
            
        }
    
        return total;
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbttn = new javax.swing.JButton();
        UserText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ShowText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        CustomerID1 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        SearchBttn = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        DateChooser1 = new com.toedter.calendar.JDateChooser();
        CustomerID = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BackBttn6 = new javax.swing.JButton();
        BackBttn7 = new javax.swing.JButton();
        BackBttn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REPORT  FORM");

        logoutbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        logoutbttn.setText("Logout");
        logoutbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbttnActionPerformed(evt);
            }
        });

        UserText.setEditable(false);
        UserText.setBackground(new java.awt.Color(0, 153, 153));
        UserText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(logoutbttn)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(0, 29, 32));

        ShowText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ShowText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTextActionPerformed(evt);
            }
        });
        ShowText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ShowTextKeyReleased(evt);
            }
        });

        ReportTable.setAutoCreateRowSorter(true);
        ReportTable.setBackground(new java.awt.Color(0, 153, 153));
        ReportTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ReportTable.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ReportTable.setForeground(new java.awt.Color(255, 255, 255));
        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale Details ID", "Sales ID", "Customer Name", "Product Name", "Category", "Sub Category", "Quantity", "Amount", "Date", "Cashier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReportTable);

        CustomerID1.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        CustomerID1.setForeground(new java.awt.Color(255, 255, 255));
        CustomerID1.setText("Total Amount ");

        Amount.setEditable(false);
        Amount.setBackground(new java.awt.Color(0, 29, 32));
        Amount.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        Amount.setForeground(new java.awt.Color(255, 255, 255));
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });

        SearchBttn.setBackground(new java.awt.Color(0, 153, 153));
        SearchBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SearchBttn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBttn.setText("Search");
        SearchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBttnActionPerformed(evt);
            }
        });

        DateChooser.setDateFormatString("yyyy-MM-dd");

        DateChooser1.setDateFormatString("yyyy-MM-dd");

        CustomerID.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        CustomerID.setForeground(new java.awt.Color(255, 255, 255));
        CustomerID.setText("To");

        jPanel5.setBackground(new java.awt.Color(0, 29, 32));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BackBttn6.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn6.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn6.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn6.setText("Employees");
        BackBttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn6ActionPerformed(evt);
            }
        });

        BackBttn7.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn7.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn7.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn7.setText("Dash Board");
        BackBttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn7ActionPerformed(evt);
            }
        });

        BackBttn9.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn9.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn9.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn9.setText("Inventory");
        BackBttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BackBttn7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackBttn6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(BackBttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBttn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(ShowText, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(DateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(SearchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(CustomerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(CustomerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(DateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTextActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_ShowTextActionPerformed

    private void ReportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportTableMouseClicked
        // TODO add your handling code here:

        

    }//GEN-LAST:event_ReportTableMouseClicked

    private void logoutbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbttnActionPerformed
        // TODO add your handling code here:
        
                LoginForm si= new LoginForm();
                si.setVisible(true);
                si.pack();
                si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
        
    }//GEN-LAST:event_logoutbttnActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void SearchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBttnActionPerformed
        // TODO add your handling code here:

          ReportTable.setModel(new DefaultTableModel(null,new String[]{"Sale Details ID","Sale ID","Customer Name","Product Name","Category","SubCategory","Quantity","Amount","Date","Cashier Name"}));
        
        
        try {
            // TODO add your handling code here:
            
            if((DateChooser.getDate()== null) || (DateChooser1.getDate()== null)){
                JOptionPane.showMessageDialog(null,"Please,Select Date.");
            }

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
          
           PreparedStatement select = (PreparedStatement) connectme
           .prepareStatement("SELECT sale_details.Sale_detail_ID,sale_details.Sales_ID,customer.Customer_Name,products.Product_Name,products.Category,\n" +
"                    inventory.SubCategory,sale_details.Sales_Quantity,sale_details.Total_Amount,sales.Sales_Date,user_login.User_Name\n" +
"                    FROM sale_details JOIN sales ON sale_details.Sales_ID=sales.Sales_ID JOIN customer ON sales.Customer_ID=customer.Customer_ID \n" +
"                    JOIN inventory ON sale_details.Prod_ID=inventory.Prod_ID JOIN products ON inventory.Product_ID=products.Product_ID JOIN user_login ON sales.Done_By=user_login.User_ID where\n" +
"                    sales.Sales_Date BETWEEN ? AND ? ORDER BY Sale_detail_ID DESC ");
          
           
           select.setString(1,((JTextField)DateChooser.getDateEditor().getUiComponent()).getText());
           select.setString(2,((JTextField)DateChooser1.getDateEditor().getUiComponent()).getText());
           //select.setString(3,UserText.getText());
           ResultSet rslt= select.executeQuery();
           
           while(rslt.next()){
               
             String ID=rslt.getString("sale_details.Sale_detail_ID");
             String I=rslt.getString("sale_details.Sales_ID");
             String N=rslt.getString("customer.Customer_Name");
             String P=rslt.getString("products.Product_Name");
             String C=rslt.getString("products.Category");
             String S=rslt.getString("inventory.SubCategory");
             String Q=rslt.getString("sale_details.Sales_Quantity");
             String A=rslt.getString("sale_details.Total_Amount");
             String D=rslt.getString("sales.Sales_Date");
             String CS=rslt.getString("user_login.User_Name");
             
             String tbData []={ID,I,N,P,C,S,Q,A,D,CS};
             DefaultTableModel tblModel= (DefaultTableModel)ReportTable.getModel();
                
             tblModel.addRow(tbData);
             
             Amount.setText(Double.toString( getSum()));
               
           }
           
           
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SearchBttnActionPerformed

    private void ShowTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShowTextKeyPressed
        // TODO add your handling code here:
        
        //DefaultTableModel tblModel=(DefaultTableModel) ReportTable.getModel();
        //TableRowSorter<DefaultTableModel> tr= new  TableRowSorter<DefaultTableModel>(tblModel);
        //ReportTable.setRowSorter(tr);
        //tr.setRowFilter(RowFilter.regexFilter(ShowText.getText().trim()));
        
    }//GEN-LAST:event_ShowTextKeyPressed

    private void ShowTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShowTextKeyReleased
        // TODO add your handling code here:
        
        
        DefaultTableModel tblModel=(DefaultTableModel) ReportTable.getModel();
        TableRowSorter <DefaultTableModel> tr= new  TableRowSorter<DefaultTableModel>(tblModel);
        ReportTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ShowText.getText().trim()));
        
    }//GEN-LAST:event_ShowTextKeyReleased

    private void BackBttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn6ActionPerformed
        // TODO add your handling code here:

       EmployeesForm si= new EmployeesForm  ();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        EmployeesForm .UserText.setText(UserText.getText());
    }//GEN-LAST:event_BackBttn6ActionPerformed

    private void BackBttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn7ActionPerformed
        // TODO add your handling code here:

        ManagerDashBoard si= new ManagerDashBoard();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ManagerDashBoard.UserText.setText(UserText.getText());
    }//GEN-LAST:event_BackBttn7ActionPerformed

    private void BackBttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn9ActionPerformed
        // TODO add your handling code here:

        ProductList si= new ProductList ();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ProductList.UserText.setText(UserText.getText());

    }//GEN-LAST:event_BackBttn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JButton BackBttn6;
    private javax.swing.JButton BackBttn7;
    private javax.swing.JButton BackBttn9;
    private javax.swing.JLabel CustomerID;
    private javax.swing.JLabel CustomerID1;
    private com.toedter.calendar.JDateChooser DateChooser;
    private com.toedter.calendar.JDateChooser DateChooser1;
    private javax.swing.JTable ReportTable;
    public static javax.swing.JButton SearchBttn;
    public static javax.swing.JTextField ShowText;
    public static javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbttn;
    // End of variables declaration//GEN-END:variables

    
}
