/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StoreKeeper;

/**
 *
 * @author AMIFAH
 */


import Login.LoginForm;
import static StoreKeeper.SupplierForm.UserText;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
public class ProductForm extends javax.swing.JFrame {

    /**
     * Creates new form ProductForm
     */
    public ProductForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbttn = new javax.swing.JButton();
        UserText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Productid = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Productname = new javax.swing.JLabel();
        Cat = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        sale1 = new javax.swing.JLabel();
        Quant = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        CatText = new javax.swing.JTextField();
        Valumetext = new javax.swing.JTextField();
        BrandText = new javax.swing.JTextField();
        SupplierText = new javax.swing.JTextField();
        UpdateBttn = new javax.swing.JButton();
        SaveBttn = new javax.swing.JButton();
        ClearBttn = new javax.swing.JButton();
        DeleteBttn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SearchText = new javax.swing.JTextField();
        CustomerID = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        SearchBttn = new javax.swing.JButton();
        SelectBttn = new javax.swing.JButton();
        Quant1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        DateChooser = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        BackBttn6 = new javax.swing.JButton();
        BackBttn7 = new javax.swing.JButton();
        BackBttn8 = new javax.swing.JButton();
        BackBttn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUCT FORM");

        logoutbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        logoutbttn.setText("Logout");
        logoutbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbttnActionPerformed(evt);
            }
        });

        UserText.setEditable(false);
        UserText.setBackground(new java.awt.Color(0, 153, 153));
        UserText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));
        UserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(476, 476, 476)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbttn)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(logoutbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 29, 32));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        Title1.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Insert/Update Product Here");

        Productid.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Productid.setForeground(new java.awt.Color(255, 255, 255));
        Productid.setText("Product ID");

        Price.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Brand");

        Productname.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Productname.setForeground(new java.awt.Color(255, 255, 255));
        Productname.setText("Product Name");

        Cat.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Cat.setForeground(new java.awt.Color(255, 255, 255));
        Cat.setText("Category");

        sub.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setText("Manuf. Date");

        sale1.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        sale1.setForeground(new java.awt.Color(255, 255, 255));
        sale1.setText("Volume");

        Quant.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Quant.setForeground(new java.awt.Color(255, 255, 255));
        Quant.setText("Supplier");

        IDText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });

        NameText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        CatText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        CatText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatTextActionPerformed(evt);
            }
        });

        Valumetext.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        Valumetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValumetextActionPerformed(evt);
            }
        });

        BrandText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        BrandText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandTextActionPerformed(evt);
            }
        });

        SupplierText.setEditable(false);
        SupplierText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SupplierText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierTextActionPerformed(evt);
            }
        });

        UpdateBttn.setBackground(new java.awt.Color(0, 153, 153));
        UpdateBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UpdateBttn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBttn.setText("Update");
        UpdateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBttnActionPerformed(evt);
            }
        });

        SaveBttn.setBackground(new java.awt.Color(0, 153, 153));
        SaveBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SaveBttn.setForeground(new java.awt.Color(255, 255, 255));
        SaveBttn.setText("Save");
        SaveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBttnActionPerformed(evt);
            }
        });

        ClearBttn.setBackground(new java.awt.Color(0, 153, 153));
        ClearBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ClearBttn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBttn.setText("Clear");
        ClearBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBttnActionPerformed(evt);
            }
        });

        DeleteBttn.setBackground(new java.awt.Color(0, 153, 153));
        DeleteBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        DeleteBttn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBttn.setText("Delete");
        DeleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBttnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 29, 32));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        SearchText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        SearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTextKeyReleased(evt);
            }
        });

        CustomerID.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        CustomerID.setForeground(new java.awt.Color(255, 255, 255));
        CustomerID.setText("Search a Product Here");

        ProTable.setAutoCreateRowSorter(true);
        ProTable.setBackground(new java.awt.Color(0, 153, 153));
        ProTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ProTable.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ProTable.setForeground(new java.awt.Color(255, 255, 255));
        ProTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Manuf. Date", "Volume", "Brand", "Description", "Supplier ID"
            }
        ));
        ProTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ProTable);

        jPanel2.setBackground(new java.awt.Color(0, 29, 9));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SupplierTable.setAutoCreateRowSorter(true);
        SupplierTable.setBackground(new java.awt.Color(0, 153, 153));
        SupplierTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        SupplierTable.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SupplierTable.setForeground(new java.awt.Color(255, 255, 255));
        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name"
            }
        ));
        SupplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SupplierTable);

        SearchBttn.setBackground(new java.awt.Color(0, 153, 153));
        SearchBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SearchBttn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBttn.setText("Select Suppliers");
        SearchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SearchBttn)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        SelectBttn.setBackground(new java.awt.Color(0, 153, 153));
        SelectBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SelectBttn.setForeground(new java.awt.Color(255, 255, 255));
        SelectBttn.setText("Select Products");
        SelectBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(SelectBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Quant1.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Quant1.setForeground(new java.awt.Color(255, 255, 255));
        Quant1.setText("Desciption");

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane2.setViewportView(Description);

        DateChooser.setDateFormatString("yyyy-MM-dd");

        jPanel5.setBackground(new java.awt.Color(0, 29, 32));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BackBttn6.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn6.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn6.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn6.setText("Supplier");
        BackBttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn6ActionPerformed(evt);
            }
        });

        BackBttn7.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn7.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn7.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn7.setText("Dash Board");
        BackBttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn7ActionPerformed(evt);
            }
        });

        BackBttn8.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn8.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn8.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn8.setText("Inventory");
        BackBttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn8ActionPerformed(evt);
            }
        });

        BackBttn9.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn9.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn9.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn9.setText("Report");
        BackBttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BackBttn7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(BackBttn6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackBttn8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(BackBttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBttn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(SaveBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(UpdateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(DeleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ClearBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sale1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Quant1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(DateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(Valumetext)
                                            .addComponent(BrandText, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SupplierText, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(Productid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(IDText))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(Productname, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(NameText))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(CatText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(Title1)))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Productid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Productname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CatText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Valumetext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sale1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BrandText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quant1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ClearBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbttnActionPerformed
        // TODO add your handling code here:
        
        LoginForm si= new LoginForm();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        
    }//GEN-LAST:event_logoutbttnActionPerformed

    private void UserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextActionPerformed

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void CatTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatTextActionPerformed

    private void ValumetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValumetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValumetextActionPerformed

    private void BrandTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandTextActionPerformed

    private void SupplierTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierTextActionPerformed

    private void UpdateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBttnActionPerformed
        // TODO add your handling code here:
        
         String id=IDText.getText();
                String name=NameText.getText();
                String cat=CatText.getText();
                //String date=DateChooser.getDate();
                String vol=Valumetext.getText();
                String brand=BrandText.getText();
                String sup=SupplierText.getText();
                String descr=Description.getText();
                
                try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");

            if((IDText.getText().equals("")) || (NameText.getText().equals("")) || (BrandText.getText().equals("")) ||
                (CatText.getText().equals("")) || (DateChooser.getDate().equals("")) || (Valumetext.getText().equals("")) || (Description.getText().equals(""))
                || (SupplierText.getText().equals(""))){

                JOptionPane.showMessageDialog(null,"Please,Fill Information First.");
            }
            else{
            PreparedStatement update = (PreparedStatement) connectme
                .prepareStatement("update products set Product_Name=?, Category=?,Year_produced=?,Volume=?,Brand=?,Product_Description=?,Supplier_ID=? where Product_ID=? ");

                   
                    update.setString(1,name);
                    update.setString(2,cat);
                    update.setString(3,((JTextField)DateChooser.getDateEditor().getUiComponent()).getText());
                    update.setString(4,vol);
                    update.setString(5,brand);
                    update.setString(6,descr);
                    update.setString(7,sup);
                    update.setString(8,id);
                    update.execute();

                DefaultTableModel tblModel=(DefaultTableModel) ProTable.getModel();
                int index=ProTable.getSelectedRow();
                SimpleDateFormat dateformat= new SimpleDateFormat("yyyy-MM-dd");
                String date= dateformat.format(DateChooser.getDate());
                
                tblModel.setValueAt(name, index, 1);
                tblModel.setValueAt(cat, index, 2);
                tblModel.setValueAt(date, index, 3);
                tblModel.setValueAt(vol, index, 4);
                tblModel.setValueAt(brand, index,5);
                tblModel.setValueAt(descr, index, 6);
                tblModel.setValueAt(sup, index, 7);

                JOptionPane.showMessageDialog(null,"Data Have Updated Successfully.");

                       
                    }

                
                
                } catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_UpdateBttnActionPerformed

    private void SaveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBttnActionPerformed
        // TODO add your handling code here:
        
                String id=IDText.getText();
                String name=NameText.getText();
                String cat=CatText.getText();
                //String date=DateChooser.getDate();
                String vol=Valumetext.getText();
                String brand=BrandText.getText();
                String sup=SupplierText.getText();
                String descr=Description.getText();
                
                try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");

            if((IDText.getText().equals("")) || (NameText.getText().equals("")) || (BrandText.getText().equals("")) ||
                (CatText.getText().equals("")) || (DateChooser.getDate().equals("")) || (Valumetext.getText().equals("")) || (Description.getText().equals(""))
                || (SupplierText.getText().equals(""))){

                JOptionPane.showMessageDialog(null,"Please,Fill Information First.");
            }
            else{
            PreparedStatement insert = (PreparedStatement) connectme
                    .prepareStatement("insert into products values(?,?,?,?,?,?,?,?)");

                    insert.setString(1,id);
                    insert.setString(2,name);
                    insert.setString(3,cat);
                    insert.setString(4,((JTextField)DateChooser.getDateEditor().getUiComponent()).getText());
                    insert.setString(5,vol);
                    insert.setString(6,brand);
                    insert.setString(7,descr);
                    insert.setString(8,sup);
                    insert.execute();

                    PreparedStatement slt = (PreparedStatement) connectme
                    .prepareStatement("select * from Products where Product_ID=? ORDER BY Product_ID DESC LIMIT 1 ");
                    
                    slt.setString(1,id);
                    ResultSet rslt= slt.executeQuery();
                    while(rslt.next()){

                        String ID=rslt.getString("Product_ID");
                        String Name=rslt.getString("Product_Name");
                        String Cate=rslt.getString("Category");
                        String Year=rslt.getString("Year_produced");
                        String Volu=rslt.getString("Volume");
                        String Brand=rslt.getString("Brand");
                        String Supp=rslt.getString("Supplier_ID");
                        String Desc=rslt.getString("Product_Description");

                        String tbData []={ID,Name,Cate,Year,Volu,Brand,Desc,Supp};
                        DefaultTableModel tblModel= (DefaultTableModel)ProTable.getModel();

                        tblModel.addRow(tbData);

                       
                    }

                }
                
                } catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_SaveBttnActionPerformed

    private void ClearBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBttnActionPerformed
        // TODO add your handling code here:
        
        ProTable.setModel(new DefaultTableModel(null,new String[]{"Product ID","Product Name","Category","Manuf. Date","Volume","Brand","Description","Supplier ID"}));
        
                IDText.setText("");
                NameText.setText("");
                CatText.setText("");
                DateChooser.setDate(null);
                Valumetext.setText("");
                BrandText.setText("");
                SupplierText.setText("");
                Description.setText("");
        
    }//GEN-LAST:event_ClearBttnActionPerformed

    private void DeleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBttnActionPerformed
        // TODO add your handling code here:
        
         String id=IDText.getText();

        try {
            // TODO add your handling code here:

            if(IDText.getText().equals("")){

                JOptionPane.showMessageDialog(null,"Please, Select Data First.");

            }
            else if(IDText.getText() != null){

                Class.forName("com.mysql.jdbc.Driver");
                Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");

                PreparedStatement delete = (PreparedStatement) connectme
                .prepareStatement("delete from products  where Product_ID=? ");

                delete.setString(1,id);
                delete.execute();

                DefaultTableModel tblModel=(DefaultTableModel) ProTable.getModel();

                if(ProTable.getSelectedRowCount()==1){

                    tblModel.removeRow(ProTable.getSelectedRow());

                    JOptionPane.showMessageDialog(null,"Data Have Deleted Successfully.");

                IDText.setText("");
                NameText.setText("");
                CatText.setText("");
                DateChooser.setDate(null);
                Valumetext.setText("");
                BrandText.setText("");
                SupplierText.setText("");
                Description.setText("");
                
                SaveBttn.setEnabled(true);

                }
                
                }

        

        } catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Can't Delete This Record,Can Affect Some Transations Occured!");
           
        }
        
    }//GEN-LAST:event_DeleteBttnActionPerformed

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed

    private void SearchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyPressed
        // TODO add your handling code here:
        
        DefaultTableModel tblModel=(DefaultTableModel) ProTable.getModel();
        TableRowSorter<DefaultTableModel> tr= new  TableRowSorter<DefaultTableModel>(tblModel);
        ProTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(SearchText.getText().trim()));
        
    }//GEN-LAST:event_SearchTextKeyPressed

    private void SearchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextKeyReleased

    private void ProTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProTableMouseClicked
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            
            
            int i=ProTable.getSelectedRow();
            DefaultTableModel Model= (DefaultTableModel)ProTable.getModel();
            IDText.setText(Model.getValueAt(i, 0).toString());
            NameText.setText(Model.getValueAt(i, 1).toString());
            CatText.setText(Model.getValueAt(i, 2).toString());
            java.util.Date date= new SimpleDateFormat("yyyy-MM-dd").parse((String)Model.getValueAt(i, 3));
            DateChooser.setDate(date);
            //DateChooser.setText(Model.getValueAt(i, 3).toString());
            Valumetext.setText(Model.getValueAt(i, 4).toString());
            BrandText.setText(Model.getValueAt(i,5).toString());
            SupplierText.setText(Model.getValueAt(i,7).toString());
            Description.setText(Model.getValueAt(i,6).toString());
            
            SaveBttn.setEnabled(false);
            
        } catch (ParseException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ProTableMouseClicked

    private void SupplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierTableMouseClicked
        // TODO add your handling code here:
        
        int i=SupplierTable.getSelectedRow();
            DefaultTableModel Model= (DefaultTableModel)SupplierTable.getModel();
            SupplierText.setText(Model.getValueAt(i, 0).toString());
            
        
    }//GEN-LAST:event_SupplierTableMouseClicked

    private void SearchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBttnActionPerformed
        // TODO add your handling code here:
        
         SupplierTable.setModel(new DefaultTableModel(null,new String[]{"Supplier ID","Supplier Name"}));
        
         try {
            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");

            PreparedStatement select = (PreparedStatement) connectme
            .prepareStatement("SELECT * FROM supplier ");

          
   
            ResultSet rslt= select.executeQuery();

            while(rslt.next()){

                String ID=rslt.getString("Supplier_ID");
                String Name=rslt.getString("Supplier_Name");
               
                

                String tbData []={ID,Name};
                DefaultTableModel tblModel= (DefaultTableModel)SupplierTable.getModel();

                tblModel.addRow(tbData);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_SearchBttnActionPerformed

    private void SelectBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBttnActionPerformed
        // TODO add your handling code here:
        
        ProTable.setModel(new DefaultTableModel(null,new String[]{"Product ID","Product Name","Category","Manuf. Date","Volume","Brand","Description","Supplier ID"}));
        
         try {
            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");

            PreparedStatement select = (PreparedStatement) connectme
            .prepareStatement("SELECT * FROM products");

            ResultSet rslt= select.executeQuery();

            while(rslt.next()){

                String ProductID=rslt.getString("Product_ID");
                String ProductName=rslt.getString("Product_Name");
                String Category=rslt.getString("Category");
                String Manu=rslt.getString("Year_Produced");
                String vol=rslt.getString("Volume");
                String Brand=rslt.getString("Brand");
                String Desc=rslt.getString("Product_Description");
                String Sup=rslt.getString("Supplier_ID");

                String tbData []={ProductID,ProductName,Category,Manu,vol,Brand,Desc,Sup};
                DefaultTableModel tblModel= (DefaultTableModel)ProTable.getModel();

                tblModel.addRow(tbData);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SelectBttnActionPerformed

    private void BackBttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn6ActionPerformed
        // TODO add your handling code here:

        SupplierForm si= new SupplierForm ();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        SupplierForm.UserText.setText(UserText.getText());
    }//GEN-LAST:event_BackBttn6ActionPerformed

    private void BackBttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn7ActionPerformed
        // TODO add your handling code here:
        
         
        StoreKeeperDashBoard si= new StoreKeeperDashBoard();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        StoreKeeperDashBoard.UserText.setText(UserText.getText());
        
    }//GEN-LAST:event_BackBttn7ActionPerformed

    private void BackBttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn8ActionPerformed
        // TODO add your handling code here:

        InventoryForm si= new InventoryForm ();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        InventoryForm.UserText.setText(UserText.getText());

    }//GEN-LAST:event_BackBttn8ActionPerformed

    private void BackBttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBttn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBttn6;
    private javax.swing.JButton BackBttn7;
    private javax.swing.JButton BackBttn8;
    private javax.swing.JButton BackBttn9;
    public static javax.swing.JTextField BrandText;
    private javax.swing.JLabel Cat;
    private javax.swing.JTextField CatText;
    private javax.swing.JButton ClearBttn;
    private javax.swing.JLabel CustomerID;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton DeleteBttn;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField IDText;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel Price;
    private javax.swing.JTable ProTable;
    private javax.swing.JLabel Productid;
    private javax.swing.JLabel Productname;
    private javax.swing.JLabel Quant;
    private javax.swing.JLabel Quant1;
    private javax.swing.JButton SaveBttn;
    public static javax.swing.JButton SearchBttn;
    private javax.swing.JTextField SearchText;
    public static javax.swing.JButton SelectBttn;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JTextField SupplierText;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton UpdateBttn;
    public static javax.swing.JTextField UserText;
    private javax.swing.JTextField Valumetext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutbttn;
    private javax.swing.JLabel sale1;
    private javax.swing.JLabel sub;
    // End of variables declaration//GEN-END:variables
}
