/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StoreKeeper;

/**
 *
 * @author AMIFAH
 */

import Login.LoginForm;
import javax.swing.JFrame;


public class StoreKeeperDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form StoreKeeperDashBoard
     */
    public StoreKeeperDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbttn = new javax.swing.JButton();
        UserText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        productbttn = new javax.swing.JButton();
        suppliersbttn = new javax.swing.JButton();
        shortbttn = new javax.swing.JButton();
        othersbttn = new javax.swing.JButton();
        shortbttn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STORE KEEPER DASHBOARD");

        logoutbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        logoutbttn.setText("Logout");
        logoutbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbttnActionPerformed(evt);
            }
        });

        UserText.setEditable(false);
        UserText.setBackground(new java.awt.Color(0, 153, 153));
        UserText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));
        UserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160)
                .addComponent(logoutbttn)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(0, 29, 32));

        productbttn.setBackground(new java.awt.Color(0, 153, 153));
        productbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        productbttn.setForeground(new java.awt.Color(255, 255, 255));
        productbttn.setText("PRODUCTS");
        productbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productbttnActionPerformed(evt);
            }
        });

        suppliersbttn.setBackground(new java.awt.Color(0, 153, 153));
        suppliersbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        suppliersbttn.setForeground(new java.awt.Color(255, 255, 255));
        suppliersbttn.setText("SUPPLIERS");
        suppliersbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersbttnActionPerformed(evt);
            }
        });

        shortbttn.setBackground(new java.awt.Color(0, 153, 153));
        shortbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        shortbttn.setForeground(new java.awt.Color(255, 255, 255));
        shortbttn.setText("INVENTORY");
        shortbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortbttnActionPerformed(evt);
            }
        });

        othersbttn.setBackground(new java.awt.Color(0, 153, 153));
        othersbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        othersbttn.setForeground(new java.awt.Color(255, 255, 255));
        othersbttn.setText("OTHER ACTIVITIES");
        othersbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersbttnActionPerformed(evt);
            }
        });

        shortbttn1.setBackground(new java.awt.Color(0, 153, 153));
        shortbttn1.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        shortbttn1.setForeground(new java.awt.Color(255, 255, 255));
        shortbttn1.setText("REPORTS");
        shortbttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortbttn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shortbttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(suppliersbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shortbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(othersbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppliersbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shortbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortbttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othersbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbttnActionPerformed
        // TODO add your handling code here:
        LoginForm si= new LoginForm();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutbttnActionPerformed

    private void UserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextActionPerformed

    private void productbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productbttnActionPerformed
        // TODO add your handling code here:

        ProductForm ic= new ProductForm ();
        ic.setVisible(true);
        ic.pack();
        ic.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ProductForm.UserText.setText(UserText.getText());

    }//GEN-LAST:event_productbttnActionPerformed

    private void shortbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortbttnActionPerformed
        // TODO add your handling code here:

        InventoryForm si= new InventoryForm();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        InventoryForm.UserText.setText(UserText.getText());

    }//GEN-LAST:event_shortbttnActionPerformed

    private void suppliersbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersbttnActionPerformed
        // TODO add your handling code here:
        
        SupplierForm si= new SupplierForm();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        SupplierForm.UserText.setText(UserText.getText());
        
    }//GEN-LAST:event_suppliersbttnActionPerformed

    private void shortbttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortbttn1ActionPerformed
        // TODO add your handling code here:
        
        StockReport si= new StockReport();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        StockReport.UserText.setText(UserText.getText());
        
    }//GEN-LAST:event_shortbttn1ActionPerformed

    private void othersbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersbttnActionPerformed
        // TODO add your handling code here:
        
        OtherActivities si= new OtherActivities ();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        OtherActivities .UserText.setText(UserText.getText());
        
    }//GEN-LAST:event_othersbttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreKeeperDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutbttn;
    private javax.swing.JButton othersbttn;
    private javax.swing.JButton productbttn;
    private javax.swing.JButton shortbttn;
    private javax.swing.JButton shortbttn1;
    private javax.swing.JButton suppliersbttn;
    // End of variables declaration//GEN-END:variables
}
