/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cashier;

import Login.LoginForm;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AMIFAH
 */
public class SaleDetails extends javax.swing.JFrame {


    /**
     * Creates new form SaleDetails
     */
    public SaleDetails() {
        initComponents();
        AmountText.setText(Double.toString( getSum()));
        
    }
    
    public double getSum(){
        
        double sum=SalesTable.getRowCount();
        double total=0;
        for (double i=0; i<sum;i++){
            total = total + Double.parseDouble(SalesTable.getValueAt((int) i, 6).toString());
            
        }
    
        return total;
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbttn = new javax.swing.JButton();
        UserText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        DetailsId = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Productid = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Productname = new javax.swing.JLabel();
        Cat = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        sale1 = new javax.swing.JLabel();
        Quant = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Dis = new javax.swing.JLabel();
        DetailsText = new javax.swing.JTextField();
        ProIDText = new javax.swing.JTextField();
        ProductText = new javax.swing.JTextField();
        CatText = new javax.swing.JTextField();
        subtext = new javax.swing.JTextField();
        SaleText = new javax.swing.JTextField();
        PriceText = new javax.swing.JTextField();
        QuantText = new javax.swing.JTextField();
        DisText = new javax.swing.JTextField();
        TotalText = new javax.swing.JTextField();
        UpdateBttn = new javax.swing.JButton();
        SaveBttn = new javax.swing.JButton();
        ClearBttn = new javax.swing.JButton();
        DeleteBttn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CustomerID = new javax.swing.JLabel();
        SearchText = new javax.swing.JTextField();
        SearchBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable();
        AmountText = new javax.swing.JTextField();
        CustomerID1 = new javax.swing.JLabel();
        TransaBttn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BackBttn3 = new javax.swing.JButton();
        FreshBttn = new javax.swing.JButton();
        SaleBttn = new javax.swing.JButton();
        BackBttn = new javax.swing.JButton();
        SaleBttn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALE DETAILS FORM");

        logoutbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        logoutbttn.setText("Logout");
        logoutbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbttnActionPerformed(evt);
            }
        });

        UserText.setEditable(false);
        UserText.setBackground(new java.awt.Color(0, 153, 153));
        UserText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));
        UserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(476, 476, 476)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbttn)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(logoutbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 29, 32));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        DetailsId.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        DetailsId.setForeground(new java.awt.Color(255, 255, 255));
        DetailsId.setText("Sale Details ID");

        Title1.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Insert Sale Details Here");

        Productid.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Productid.setForeground(new java.awt.Color(255, 255, 255));
        Productid.setText("Product ID");

        Price.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Price");

        Productname.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Productname.setForeground(new java.awt.Color(255, 255, 255));
        Productname.setText("Product Name");

        Cat.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Cat.setForeground(new java.awt.Color(255, 255, 255));
        Cat.setText("Category");

        sub.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setText("Sub Category");

        sale1.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        sale1.setForeground(new java.awt.Color(255, 255, 255));
        sale1.setText("Sale  ID");

        Quant.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Quant.setForeground(new java.awt.Color(255, 255, 255));
        Quant.setText("Quantity ");

        Total.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("Total Price");

        Dis.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        Dis.setForeground(new java.awt.Color(255, 255, 255));
        Dis.setText("Discount %");

        DetailsText.setEditable(false);
        DetailsText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        DetailsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsTextActionPerformed(evt);
            }
        });

        ProIDText.setEditable(false);
        ProIDText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ProIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProIDTextActionPerformed(evt);
            }
        });

        ProductText.setEditable(false);
        ProductText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ProductText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductTextActionPerformed(evt);
            }
        });

        CatText.setEditable(false);
        CatText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        CatText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatTextActionPerformed(evt);
            }
        });

        subtext.setEditable(false);
        subtext.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        subtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtextActionPerformed(evt);
            }
        });

        SaleText.setEditable(false);
        SaleText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SaleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleTextActionPerformed(evt);
            }
        });

        PriceText.setEditable(false);
        PriceText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        PriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTextActionPerformed(evt);
            }
        });

        QuantText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        QuantText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantTextActionPerformed(evt);
            }
        });

        DisText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        DisText.setText("0");
        DisText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisTextActionPerformed(evt);
            }
        });

        TotalText.setEditable(false);
        TotalText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        TotalText.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TotalTextMouseMoved(evt);
            }
        });
        TotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTextActionPerformed(evt);
            }
        });

        UpdateBttn.setBackground(new java.awt.Color(0, 153, 153));
        UpdateBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UpdateBttn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBttn.setText("Update");
        UpdateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBttnActionPerformed(evt);
            }
        });

        SaveBttn.setBackground(new java.awt.Color(0, 153, 153));
        SaveBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SaveBttn.setForeground(new java.awt.Color(255, 255, 255));
        SaveBttn.setText("Save");
        SaveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBttnActionPerformed(evt);
            }
        });

        ClearBttn.setBackground(new java.awt.Color(0, 153, 153));
        ClearBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ClearBttn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBttn.setText("Clear");
        ClearBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBttnActionPerformed(evt);
            }
        });

        DeleteBttn.setBackground(new java.awt.Color(0, 153, 153));
        DeleteBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        DeleteBttn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBttn.setText("Delete");
        DeleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBttnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 29, 32));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CustomerID.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        CustomerID.setForeground(new java.awt.Color(255, 255, 255));
        CustomerID.setText("Search a Product Here");

        SearchText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        SearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTextKeyReleased(evt);
            }
        });

        SearchBttn.setBackground(new java.awt.Color(0, 153, 153));
        SearchBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SearchBttn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBttn.setText("Search");
        SearchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBttnActionPerformed(evt);
            }
        });

        ProTable.setAutoCreateRowSorter(true);
        ProTable.setBackground(new java.awt.Color(0, 153, 153));
        ProTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ProTable.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ProTable.setForeground(new java.awt.Color(255, 255, 255));
        ProTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Catogory", "Sub Category", "Price"
            }
        ));
        ProTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 29, 32));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        SalesTable.setAutoCreateRowSorter(true);
        SalesTable.setBackground(new java.awt.Color(0, 153, 153));
        SalesTable.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SalesTable.setForeground(new java.awt.Color(255, 255, 255));
        SalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale_Details_ID", "Prod_ID", "Sales_ID", "Unit Price", "Quantity", "Discount", "Total Price"
            }
        ));
        SalesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(SalesTable);

        AmountText.setEditable(false);
        AmountText.setBackground(new java.awt.Color(0, 29, 32));
        AmountText.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        AmountText.setForeground(new java.awt.Color(255, 255, 255));
        AmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountTextActionPerformed(evt);
            }
        });

        CustomerID1.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        CustomerID1.setForeground(new java.awt.Color(255, 255, 255));
        CustomerID1.setText("Total Amount To Pay Is");

        TransaBttn.setBackground(new java.awt.Color(0, 153, 153));
        TransaBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        TransaBttn.setForeground(new java.awt.Color(255, 255, 255));
        TransaBttn.setText("View/Refresh Transactions");
        TransaBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(TransaBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(CustomerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TransaBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        jPanel6.setBackground(new java.awt.Color(0, 29, 32));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BackBttn3.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn3.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn3.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn3.setText("Dash Board");
        BackBttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn3ActionPerformed(evt);
            }
        });

        FreshBttn.setBackground(new java.awt.Color(0, 153, 153));
        FreshBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        FreshBttn.setForeground(new java.awt.Color(255, 255, 255));
        FreshBttn.setText("Report");
        FreshBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreshBttnActionPerformed(evt);
            }
        });

        SaleBttn.setBackground(new java.awt.Color(0, 153, 153));
        SaleBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SaleBttn.setForeground(new java.awt.Color(255, 255, 255));
        SaleBttn.setText("Sale Data");
        SaleBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleBttnActionPerformed(evt);
            }
        });

        BackBttn.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        BackBttn.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn.setText("Back");
        BackBttn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackBttnMouseMoved(evt);
            }
        });
        BackBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttnActionPerformed(evt);
            }
        });

        SaleBttn1.setBackground(new java.awt.Color(0, 153, 153));
        SaleBttn1.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SaleBttn1.setForeground(new java.awt.Color(255, 255, 255));
        SaleBttn1.setText("Product List");
        SaleBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleBttn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(BackBttn3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(SaleBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(SaleBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FreshBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FreshBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaleBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaleBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(SaveBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClearBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Productid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ProIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(DetailsId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(PriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Productname, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ProductText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CatText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(subtext, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(sale1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SaleText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(QuantText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DisText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(DetailsId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(DetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Productid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Productname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CatText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sale1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaleText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuantText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextActionPerformed

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
        
        
       

    }//GEN-LAST:event_SearchTextActionPerformed

    private void BackBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttnActionPerformed
        // TODO add your handling code here:
        
        if(evt.getSource()==BackBttn){
        String SalesID=SaleText.getText();
        
        if(UserText.getText().equals("")){
            
            BackBttn.setEnabled(false);
        }
        else{
            
               
                Insertcustomer ic= new Insertcustomer();
                ic.setVisible(true);
                ic.pack();
                ic.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
                Insertcustomer.UserText.setText(UserText.getText());
           
          
       
        }
        }  
    }//GEN-LAST:event_BackBttnActionPerformed

    private void SaleBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleBttnActionPerformed
        // TODO add your handling code here
        
                SalesInfo si= new SalesInfo();
                si.setVisible(true);
                si.pack();
                si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
                SalesInfo.UserText.setText(SaleDetails.UserText.getText());
        
    }//GEN-LAST:event_SaleBttnActionPerformed

    private void BackBttnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBttnMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BackBttnMouseMoved

    private void DetailsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DetailsTextActionPerformed

    private void UpdateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBttnActionPerformed
        // TODO add your handling code here:
        
        String id=DetailsText.getText();
        String dis=DisText.getText();
        String qu=QuantText.getText();
       String to= TotalText.getText();
        
        
         try {
            // TODO add your handling code here:
            
            if(DetailsText.getText().equals("")){
            
                JOptionPane.showMessageDialog(null,"Please, Select Data First.");
                
            }
            else if(DetailsText.getText() != null){
                
             Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
          
           PreparedStatement update = (PreparedStatement) connectme
           .prepareStatement("update sale_details set Sales_Quantity=?, Discount=?,Total_Amount=? where Sale_detail_ID=? ");
           
           update.setString(1,qu);
           update.setString(2,dis);
           update.setString(3,to);
           update.setString(4,id);
           update.execute();
           
           DefaultTableModel tblModel=(DefaultTableModel) SalesTable.getModel();
           int index=SalesTable.getSelectedRow();
           tblModel.setValueAt(qu, index, 4);
           tblModel.setValueAt(dis, index, 5);
           tblModel.setValueAt(to, index, 6);
           
           
           JOptionPane.showMessageDialog(null,"Data Have Updated Successfully.");
           
           AmountText.setText(Double.toString( getSum()));
      
            }
            
            else{
               JOptionPane.showMessageDialog(null,""); 
            }
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UpdateBttnActionPerformed

    private void ProIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProIDTextActionPerformed

    private void ProductTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductTextActionPerformed

    private void CatTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatTextActionPerformed

    private void PriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTextActionPerformed

    private void QuantTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantTextActionPerformed

    private void DisTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisTextActionPerformed

    private void TotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTextActionPerformed

    private void SaveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBttnActionPerformed
        // TODO add your handling code here:
        
        String ProID=ProIDText.getText();
        String SaleID=SaleText.getText();
        String Price=PriceText.getText();
        String Quantity=QuantText.getText();
        String Discount=DisText.getText();
        String Total=TotalText.getText();
        
        try{
                Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
          
         PreparedStatement Check = (PreparedStatement) connectme
           .prepareStatement("SELECT Product_Name, Quantity_in_stock FROM products JOIN inventory ON inventory.Product_ID=products.Product_ID WHERE inventory.Prod_ID=?");
   
           Check.setString(1,ProID);
           ResultSet Checkit= Check.executeQuery();
        
            
            
            if((ProIDText.getText().equals("")) || (SaleText.getText().equals("")) ||
                    (PriceText.getText().equals("")) || (QuantText.getText().equals("")) 
                    || (TotalText.getText().equals(""))){
                
                
               
               JOptionPane.showMessageDialog(null,"Please,Fill Information First.");
            }
            if(Checkit.next()){
                
                String namee=Checkit.getString("Product_Name");
               int qtty=Integer.parseInt(Quantity);
               String Qntt=Checkit.getString("Quantity_in_stock");
               int qtty1=Integer.parseInt(Qntt);
                
           if(qtty1 < qtty){
               
               JOptionPane.showMessageDialog(null,"Sorry!The stock has only " +Qntt+ " of The"+namee );
               
           }
           
            else{
            
        
            // TODO add your handling code here:
            

            
           PreparedStatement insert = (PreparedStatement) connectme
           .prepareStatement("insert into sale_details values(null,?,?,?,?,?,?)");
           
           
           insert.setString(1,ProID);
           insert.setString(2,SaleID);
           insert.setString(3,Price);
           insert.setString(4,Quantity);
           insert.setString(5,Discount);
           insert.setString(6,Total);
           insert.execute();
           
            PreparedStatement slt = (PreparedStatement) connectme
           .prepareStatement("select * from sale_details ORDER BY Sale_Detail_ID DESC LIMIT 1");
           
           
           ResultSet rslt= slt.executeQuery();
            while(rslt.next()){
               
             String Sales=rslt.getString("Sale_Detail_ID");
             String ProductID=rslt.getString("Prod_ID");
             String Sale=String.valueOf(rslt.getInt("Sales_ID"));
             String Unit=String.valueOf(rslt.getDouble("Unit_Price"));
             String Qnty=String.valueOf(rslt.getInt("Sales_Quantity"));
             String Disc=String.valueOf(rslt.getDouble("Discount"));
             String Totalll=String.valueOf(rslt.getDouble("Total_Amount"));
             
             String tbData []={Sales,ProductID,Sale,Unit,Qnty,Disc,Totalll};
             DefaultTableModel tblModel= (DefaultTableModel)SalesTable.getModel();
                
             tblModel.addRow(tbData);
             
             AmountText.setText(Double.toString( getSum()));
           }
               
        }
                
            }
            
           
                          

          
         
    }
        
        catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveBttnActionPerformed

    private void ClearBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBttnActionPerformed
        // TODO add your handling code here:
       
         if(evt.getSource()==ClearBttn){
           
        ProIDText.setText("");
        DetailsText.setText("");
        ProductText.setText("");
        CatText.setText("");
        subtext.setText("");
        PriceText.setText("");
        QuantText.setText("");
        DisText.setText("0");
        TotalText.setText("");
        }
        
    }//GEN-LAST:event_ClearBttnActionPerformed

    private void DeleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBttnActionPerformed
            // TODO add your handling code here:
        
         String id=DetailsText.getText();
        
        
         try {
            // TODO add your handling code here:
            
            if(DetailsText.getText().equals("")){
            
                JOptionPane.showMessageDialog(null,"Please, Select Data First.");
                
            }
            else if(DetailsText.getText() != null){
            

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
 
           PreparedStatement delete = (PreparedStatement) connectme
             .prepareStatement("delete from sale_details  where Sale_detail_ID=? ");
           
          
           delete.setString(1,id);
           delete.execute();
           
           DefaultTableModel tblModel=(DefaultTableModel) SalesTable.getModel();
           
           if(SalesTable.getSelectedRowCount()==1){
           
               tblModel.removeRow(SalesTable.getSelectedRow());
               
                JOptionPane.showMessageDialog(null,"Data Have Deleted Successfully.");
                
                AmountText.setText(Double.toString( getSum()));
           
           }
           else{
               if(SalesTable.getRowCount()==0){
                   
                   
               }
           }
           
         
          
         
        DetailsText.setText("");
        DisText.setText("0");
        QuantText.setText("");
        PriceText.setText("");
        ProIDText.setText("");
        TotalText.setText("");
        
       
        
            }
            
            else{
               JOptionPane.showMessageDialog(null,"Can't Delete This Record,Can Affect Some Transations Occured!"); 
            }
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        
    }//GEN-LAST:event_DeleteBttnActionPerformed

    private void SearchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBttnActionPerformed
        // TODO add your handling code here:
        
        ProTable.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Category","SubCategory","Price"}));
          String name=SearchText.getText();
        String category=SearchText.getText();
        
        
        try {
            // TODO add your handling code here:
            
            if(SearchText.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please,Insert Something in Search Field.");
            }

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
          
           PreparedStatement select = (PreparedStatement) connectme
           .prepareStatement("SELECT * FROM products JOIN inventory ON inventory.Product_ID=products.Product_ID WHERE products.Product_Name=? OR products.Category=?");
          
           
           select.setString(1,name);
           select.setString(2,category);
           ResultSet rslt= select.executeQuery();
           
           while(rslt.next()){
               
             String ProductID=rslt.getString("Prod_ID");
             String ProductName=rslt.getString("Product_Name");
             String Category=rslt.getString("Category");
             String Sub=rslt.getString("SubCategory");
             String Price=rslt.getString("Demand_Price");
             
             String tbData []={ProductID,ProductName,Category,Sub,Price};
             DefaultTableModel tblModel= (DefaultTableModel)ProTable.getModel();
                
             tblModel.addRow(tbData);
             
             
               
           }
           
           
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SaleDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_SearchBttnActionPerformed

    private void ProTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProTableMouseClicked
        // TODO add your handling code here:
        
         QuantText.setText("");
        DisText.setText("0");
        TotalText.setText("");
        
        
        int i=ProTable.getSelectedRow();
        TableModel Model= ProTable.getModel();
        ProIDText.setText(Model.getValueAt(i, 0).toString());
        ProductText.setText(Model.getValueAt(i, 1).toString());
        CatText.setText(Model.getValueAt(i, 2).toString());
        subtext.setText(Model.getValueAt(i, 3).toString());
        PriceText.setText(Model.getValueAt(i, 4).toString());
        
         SaveBttn.setEnabled(true);
        
    }//GEN-LAST:event_ProTableMouseClicked

    private void SaleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaleTextActionPerformed

    private void subtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtextActionPerformed

    private void TotalTextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalTextMouseMoved
        // TODO add your handling code here:
        
        try{
        
        String Pricee=PriceText.getText();
        double pri=Double.parseDouble(Pricee);
        String Quantit=QuantText.getText();
        double qua=Double.parseDouble(Quantit);
        String Disc=DisText.getText();
        double dis=Double.parseDouble(Disc);
        
        double Mult=pri*qua;
        double Tota=Mult - (Mult*dis/100) ;
        String Total=new Double(Tota).toString();
        
        
        TotalText.setText(Total);
        }
        catch (Exception ex) {
            //Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_TotalTextMouseMoved

    private void SalesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesTableMouseClicked
        // TODO add your handling code here:
        
        int i=SalesTable.getSelectedRow();
        TableModel Model= SalesTable.getModel();
        DetailsText.setText(Model.getValueAt(i, 0).toString());
        ProIDText.setText(Model.getValueAt(i, 1).toString());
        SaleText.setText(Model.getValueAt(i, 2).toString());
        PriceText.setText(Model.getValueAt(i, 3).toString());
        QuantText.setText(Model.getValueAt(i, 4).toString());
        DisText.setText(Model.getValueAt(i, 5).toString());
        TotalText.setText(Model.getValueAt(i, 6).toString());
        
        SaveBttn.setEnabled(false);
        
        
    }//GEN-LAST:event_SalesTableMouseClicked

    private void FreshBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreshBttnActionPerformed
        // TODO add your handling code here:
        
        ReportForm si= new ReportForm();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ReportForm.UserText.setText(UserText.getText());
                                          
        
    }//GEN-LAST:event_FreshBttnActionPerformed

    private void AmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountTextActionPerformed

    private void SearchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyPressed
        // TODO add your handling code here:
        
            
               /*int rows=SalesTable.getRowCount();
               for (int i = rows - 1; i>=0; i--){
            
                   SalesTable.removeRow(i);
                   
        }*/
            
            /*DefaultTableModel tblModel=(DefaultTableModel) ProTable.getModel();
            TableRowSorter<DefaultTableModel> tr= new  TableRowSorter<DefaultTableModel>(tblModel);
            ProTable.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(SearchText.getText().trim()));*/
           
           
     
    
    }//GEN-LAST:event_SearchTextKeyPressed

    private void SearchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyReleased
        // TODO add your handling code here:
        
         DefaultTableModel tblModel=(DefaultTableModel) ProTable.getModel();
           
            
            while(tblModel.getRowCount()>0){
                
                tblModel.removeRow(0);
            }
    }//GEN-LAST:event_SearchTextKeyReleased

    private void TransaBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaBttnActionPerformed
        // TODO add your handling code here:
        
        SalesTable.setModel(new DefaultTableModel(null,new String[]{"Sale_Details_ID","Prod_ID","Sales_ID","Unit Price","Quantity","Discount","Total Price"}));
        
        String saleId=SaleText.getText();
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
          
         PreparedStatement slt = (PreparedStatement) connectme
           .prepareStatement("select * from sale_details where Sales_ID=? ORDER BY Sales_ID DESC");
           
           slt.setString(1,saleId);
           ResultSet rslt= slt.executeQuery();
            while(rslt.next()){
               
             String Sales=rslt.getString("Sale_Detail_ID");
             String ProductID=rslt.getString("Prod_ID");
             String Sale=String.valueOf(rslt.getInt("Sales_ID"));
             String Unit=String.valueOf(rslt.getDouble("Unit_Price"));
             String Qnty=String.valueOf(rslt.getInt("Sales_Quantity"));
             String Disc=String.valueOf(rslt.getDouble("Discount"));
             String Totalll=String.valueOf(rslt.getDouble("Total_Amount"));
             
             String tbData []={Sales,ProductID,Sale,Unit,Qnty,Disc,Totalll};
             DefaultTableModel tblModel= (DefaultTableModel)SalesTable.getModel();
                
             tblModel.addRow(tbData);
             
             AmountText.setText(Double.toString( getSum()));
           }
        }
         catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(SaleDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No Selected Data");
        }
        
    }//GEN-LAST:event_TransaBttnActionPerformed

    private void logoutbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbttnActionPerformed
        // TODO add your handling code here:
        
                LoginForm si= new LoginForm();
                si.setVisible(true);
                si.pack();
                si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
        
    }//GEN-LAST:event_logoutbttnActionPerformed

    private void BackBttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn3ActionPerformed
        // TODO add your handling code here:

        CashierDashBoard si= new CashierDashBoard();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        CashierDashBoard.UserText.setText(SaleDetails.UserText.getText());
    }//GEN-LAST:event_BackBttn3ActionPerformed

    private void SaleBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleBttn1ActionPerformed
        // TODO add your handling code here:

        ProductList si= new ProductList();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ProductList.UserText.setText(UserText.getText());

    }//GEN-LAST:event_SaleBttn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountText;
    private javax.swing.JButton BackBttn;
    private javax.swing.JButton BackBttn3;
    private javax.swing.JLabel Cat;
    private javax.swing.JTextField CatText;
    private javax.swing.JButton ClearBttn;
    private javax.swing.JLabel CustomerID;
    private javax.swing.JLabel CustomerID1;
    private javax.swing.JButton DeleteBttn;
    private javax.swing.JLabel DetailsId;
    private javax.swing.JTextField DetailsText;
    private javax.swing.JLabel Dis;
    private javax.swing.JTextField DisText;
    private javax.swing.JButton FreshBttn;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceText;
    private javax.swing.JTextField ProIDText;
    private javax.swing.JTable ProTable;
    private javax.swing.JTextField ProductText;
    private javax.swing.JLabel Productid;
    private javax.swing.JLabel Productname;
    private javax.swing.JLabel Quant;
    private javax.swing.JTextField QuantText;
    private javax.swing.JButton SaleBttn;
    private javax.swing.JButton SaleBttn1;
    public static javax.swing.JTextField SaleText;
    private javax.swing.JTable SalesTable;
    private javax.swing.JButton SaveBttn;
    public static javax.swing.JButton SearchBttn;
    private javax.swing.JTextField SearchText;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Total;
    private javax.swing.JTextField TotalText;
    private javax.swing.JButton TransaBttn;
    private javax.swing.JButton UpdateBttn;
    public static javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutbttn;
    private javax.swing.JLabel sale1;
    private javax.swing.JLabel sub;
    private javax.swing.JTextField subtext;
    // End of variables declaration//GEN-END:variables

    private static class DriverManager {

        public DriverManager() {
        }
    }

    private static class tbModel {


        private static void addRow(String[] tbData) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }


        public tbModel() {
        }
    }

    private static class DbUtils {

        private static TableModel ResultSetToTableModel(ResultSet rslt) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public DbUtils() {
        }
    }
}
