/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cashier;

import Login.LoginForm;
import static cashier.Insertcustomer.UserText;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AMIFAH
 */
public class SalesInfo extends javax.swing.JFrame {

    /**
     * Creates new form SalesInFo
     */
    public SalesInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbttn = new javax.swing.JButton();
        UserText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ShowBttn = new javax.swing.JButton();
        ShowText = new javax.swing.JTextField();
        DeleteBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        BackBttn1 = new javax.swing.JButton();
        SaleBttn1 = new javax.swing.JButton();
        BackBttn9 = new javax.swing.JButton();
        BackBttn = new javax.swing.JButton();
        TosaleBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALE REVIEW FORM");

        logoutbttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        logoutbttn.setText("Logout");
        logoutbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbttnActionPerformed(evt);
            }
        });

        UserText.setEditable(false);
        UserText.setBackground(new java.awt.Color(0, 153, 153));
        UserText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbttn)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(0, 29, 32));

        ShowBttn.setBackground(new java.awt.Color(0, 153, 153));
        ShowBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ShowBttn.setForeground(new java.awt.Color(255, 255, 255));
        ShowBttn.setText("Show Sales info");
        ShowBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBttnActionPerformed(evt);
            }
        });

        ShowText.setEditable(false);
        ShowText.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        ShowText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTextActionPerformed(evt);
            }
        });

        DeleteBttn.setBackground(new java.awt.Color(0, 153, 153));
        DeleteBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        DeleteBttn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBttn.setText("Delete");
        DeleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBttnActionPerformed(evt);
            }
        });

        SalesTable.setAutoCreateRowSorter(true);
        SalesTable.setBackground(new java.awt.Color(0, 153, 153));
        SalesTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        SalesTable.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SalesTable.setForeground(new java.awt.Color(255, 255, 255));
        SalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Sales Date", "Customer Name"
            }
        ));
        SalesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SalesTable);

        jPanel5.setBackground(new java.awt.Color(0, 29, 32));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BackBttn1.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn1.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn1.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn1.setText("Dash Board");
        BackBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn1ActionPerformed(evt);
            }
        });

        SaleBttn1.setBackground(new java.awt.Color(0, 153, 153));
        SaleBttn1.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        SaleBttn1.setForeground(new java.awt.Color(255, 255, 255));
        SaleBttn1.setText("Product List");
        SaleBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleBttn1ActionPerformed(evt);
            }
        });

        BackBttn9.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn9.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn9.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn9.setText("Report");
        BackBttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttn9ActionPerformed(evt);
            }
        });

        BackBttn.setBackground(new java.awt.Color(0, 153, 153));
        BackBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        BackBttn.setForeground(new java.awt.Color(255, 255, 255));
        BackBttn.setText("Customer");
        BackBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BackBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BackBttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(SaleBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaleBttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        TosaleBttn.setBackground(new java.awt.Color(0, 153, 153));
        TosaleBttn.setFont(new java.awt.Font("Footlight MT Light", 0, 15)); // NOI18N
        TosaleBttn.setForeground(new java.awt.Color(255, 255, 255));
        TosaleBttn.setText("Next to sale details");
        TosaleBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TosaleBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ShowText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ShowBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TosaleBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ShowText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ShowBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(DeleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TosaleBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBttnActionPerformed
        // TODO add your handling code here:

        String name=UserText.getText();
        

        try {
            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");

            PreparedStatement select = (PreparedStatement) connectme
            .prepareStatement("select * from sales join customer on sales.Customer_ID=customer.Customer_ID where sales.Done_By=?");

            select.setString(1,name);
            ResultSet rslt= select.executeQuery();

            while(rslt.next()){

             String ID=rslt.getString("Sales_ID");
             String Date=rslt.getString("Sales_Date");
             String Cust=rslt.getString("Customer_Name");
             
             
             String tbData []={ID,Date,Cust};
             DefaultTableModel tblModel= (DefaultTableModel)SalesTable.getModel();
                
             tblModel.addRow(tbData);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ShowBttnActionPerformed

    private void DeleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBttnActionPerformed
        // TODO add your handling code here:
        
          String id=ShowText.getText();
        
        
         try {
            // TODO add your handling code here:
            
            if(ShowText.getText().equals("")){
            
                JOptionPane.showMessageDialog(null,"Please, Select Data First.");
                
            }
             if(ShowText.getText() != null){
            

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
 
           PreparedStatement delete = (PreparedStatement) connectme
             .prepareStatement("delete from sales  where Sales_ID=? ");
           
          
           delete.setString(1,id);
           delete.execute();
           
           DefaultTableModel tblModel=(DefaultTableModel) SalesTable.getModel();
           
           if(SalesTable.getSelectedRowCount()==1){
           
               tblModel.removeRow(SalesTable.getSelectedRow());
               
                JOptionPane.showMessageDialog(null,"Data Have Deleted Successfully.");
                
           
           }
       
            }
            
            
          
        } catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Can't Delete This Record,Can Affect Some Transations Occured!");
           
        }
        
    }//GEN-LAST:event_DeleteBttnActionPerformed

    private void BackBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttnActionPerformed
        // TODO add your handling code here:
        
                Insertcustomer si= new Insertcustomer();
                si.setVisible(true);
                si.pack();
                si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
                Insertcustomer.UserText.setText(SalesInfo.UserText.getText());
        
    }//GEN-LAST:event_BackBttnActionPerformed

    private void TosaleBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TosaleBttnActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            
            if(ShowText.getText().equals("")){
            
                JOptionPane.showMessageDialog(null,"Please, Select Data First.");
                
            }
            else{
            String id=ShowText.getText();

            Class.forName("com.mysql.jdbc.Driver");
            Connection connectme=DriverManager.getConnection("jdbc:mysql://localhost:3306/wine_liquor_store", "root","");
          
           PreparedStatement update = (PreparedStatement) connectme
           .prepareStatement("update sales set Sales_Date=NOW() where Sales_ID=? ");
           
           update.setString(1,id);
           update.execute();
           
           
                SaleDetails si= new  SaleDetails();
                si.setVisible(true);
                si.pack();
                si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
                SaleDetails.SaleText.setText(SalesInfo.ShowText.getText());
                 SaleDetails.UserText.setText(SalesInfo.UserText.getText());
            }
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Insertcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

            
                                              

   
      
    }//GEN-LAST:event_TosaleBttnActionPerformed

    private void SalesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesTableMouseClicked
        // TODO add your handling code here:
        
        int i=SalesTable.getSelectedRow();
        TableModel Model= SalesTable.getModel();
        ShowText.setText(Model.getValueAt(i, 0).toString());
        
    }//GEN-LAST:event_SalesTableMouseClicked

    private void ShowTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ShowTextActionPerformed

    private void logoutbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbttnActionPerformed
        // TODO add your handling code here:
        
                LoginForm si= new LoginForm();
                si.setVisible(true);
                si.pack();
                si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
        
    }//GEN-LAST:event_logoutbttnActionPerformed

    private void BackBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn1ActionPerformed
        // TODO add your handling code here:

        CashierDashBoard si= new CashierDashBoard();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        CashierDashBoard.UserText.setText(UserText.getText());
    }//GEN-LAST:event_BackBttn1ActionPerformed

    private void SaleBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleBttn1ActionPerformed
        // TODO add your handling code here:

        ProductList si= new ProductList();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ProductList.UserText.setText(UserText.getText());
    }//GEN-LAST:event_SaleBttn1ActionPerformed

    private void BackBttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttn9ActionPerformed
        // TODO add your handling code here:

        ReportForm si= new ReportForm ();
        si.setVisible(true);
        si.pack();
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ReportForm.UserText.setText(UserText.getText());

    }//GEN-LAST:event_BackBttn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBttn;
    private javax.swing.JButton BackBttn1;
    private javax.swing.JButton BackBttn9;
    private javax.swing.JButton DeleteBttn;
    private javax.swing.JButton SaleBttn1;
    private javax.swing.JTable SalesTable;
    private javax.swing.JButton ShowBttn;
    public static javax.swing.JTextField ShowText;
    private javax.swing.JButton TosaleBttn;
    public static javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbttn;
    // End of variables declaration//GEN-END:variables
}
